### ISSUE TITLE
Not compatible with Cold Sweat 2.3.10

### ISSUE THREAD

**Issue by xiaojuzi122** [AtobaAzul/TFC-ColdSweat#2]
Not compatible with Cold Sweat 2.3.10, go back to 2.3.9 to launch the game normally
Here's the bug report
[错误报告-2024-12-24_17.27.23.zip](https://github.com/user-attachments/files/18238225/-2024-12-24_17.27.23.zip)

**Comment by AtobaAzul** [comment]
This issue was already fixed but i cant push an update until I get back home after the holidays.
